title: MABS 2024 - The 25th International Workshop on Multi-Agent-Based Simulation
email: mabs2024@easychair.org

description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/mabs2024" # the subpath of your site, e.g. /blog
url: "https://mabsworkshop.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: MABS2024
  email: "mabs2024@easychair.org"

header_pages:
   - committees.md
   - call_for_papers.md
   - accepted_papers.md
   - registration.md
   - program.md
#  - invited.md
#  - postproceedings.md
   - mabs_series.md
  
# Build settings
theme: minima
